repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^src/cliffordstf/
        additional_dependencies:
          - numpy
          - omegaconf
          - hydra-core
          - torch

  - repo: local
    hooks:
      - id: check-anonymity
        name: check-anonymity
        entry: python tools/check_anonymity.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
